# Welcome to Bridgetown!
#
# This config file is for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec bridgetown serve'. If you change this file, please restart the
# server process.
#
# For reloadable site metadata like title, SEO description, social media
# handles, etc., take a look at src/_data/site_metadata.yml
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#

url: "https://2023.euruko.org" # the base hostname & protocol for your site, e.g. https://example.com

permalink: pretty

content_engine: resource

# Other options you might want to investigate:

base_path: "/" # the subpath of your site, e.g. /blog
timezone: Europe/Vilnius
# pagination:
#   enabled: true

defaults:
  # - values:
  #     layout: "default"
  - scope:
      collection: "talks"
    values:
      layout: "talk"

collections:
  speakers:
    output: false
    relations:
      has_one: talk
  talks:
    layout: page
    permalink: /schedule/:group/:speaker_or_slug/
    output: true
    relations:
      belongs_to:
        - speaker
        - sponsor
  benefits:
    output: false
  sponsors:
    output: false
    relations:
      has_many: talks
  jobs:
    output: false

include:
  - .nojekyll
  - _redirects
  - _headers
